# Generated by Django 5.2.13 on 2026-04-17 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.SlugField(help_text='Slug of the CoursePage this progress belongs to.', max_length=200)),
                ('payload', models.JSONField(default=dict, help_text='Frontend-defined progress blob (mirrors CourseProgress in the React store).')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course progress',
                'verbose_name_plural': 'Course progress',
                'indexes': [models.Index(fields=['user', 'course_slug'], name='progress_co_user_id_87cce2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course_slug'), name='unique_user_course_progress')],
            },
        ),
    ]
