# Generated by Django 5.2.13 on 2026-04-17 23:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Optional. Leave blank for untimed.', null=True)),
            ],
            options={
                'verbose_name': 'Assessment',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CourseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Course catalog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('cpe_credits', models.DecimalField(decimal_places=1, default=1.0, help_text='Credits awarded on completion. Informational for internal training.', max_digits=4)),
                ('passing_score', models.PositiveSmallIntegerField(default=70, help_text='Minimum percentage required to pass the assessment.')),
            ],
            options={
                'verbose_name': 'Course',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EvaluationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evaluation',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ModulePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField()),
                ('sections', wagtail.fields.StreamField([('section', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('apps.courses.blocks.ParagraphBlock', (), {}), 2: ('apps.courses.blocks.HeadingBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('tip', 'Tip'), ('warning', 'Warning'), ('important', 'Important')]}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('body', 4), ('variant', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Example', 'max_length': 120, 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 7), ('body', 4)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Important', 'max_length': 120, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('title', 9), ('body', 4)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Header', 'max_length': 120}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Cell'}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Row'}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Rows'}), 16: ('wagtail.blocks.StructBlock', [[('headers', 12), ('rows', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Item', 'max_length': 500}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('items', 18)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('heading', 2), ('callout', 6), ('example', 8), ('warning', 10), ('table', 16), ('bullet_list', 19)]], {'required': True}), 21: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 20)]], {})}, help_text='Add titled sections, then drop content blocks (paragraph, callout, table, etc.) into each.')),
            ],
            options={
                'verbose_name': 'Module',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Review (knowledge check)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', wagtail.fields.RichTextField()),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('explanation', wagtail.fields.RichTextField()),
                ('module_reference', models.CharField(blank=True, help_text="Free-text reference back to the source module (e.g. 'Module 1 — Section 2').", max_length=200)),
                ('assessment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.assessmentpage')),
            ],
            options={
                'verbose_name': 'Assessment question',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('question', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.assessmentquestion')),
            ],
            options={
                'verbose_name': 'Answer option',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseLearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=500)),
                ('course', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='courses.coursepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('likert', 'Likert (1–5 rating)'), ('text', 'Free-text response')], default='likert', max_length=10)),
                ('evaluation', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.evaluationpage')),
            ],
            options={
                'verbose_name': 'Evaluation question',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleLearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=500)),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='courses.modulepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', wagtail.fields.RichTextField()),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('feedback_correct', wagtail.fields.RichTextField(help_text='Shown when the learner picks the right option.')),
                ('feedback_incorrect', wagtail.fields.RichTextField(help_text='Shown when the learner picks a wrong option.')),
                ('explanation', wagtail.fields.RichTextField(help_text='Always shown after the answer is locked.')),
                ('review', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.reviewpage')),
            ],
            options={
                'verbose_name': 'Review question',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('question', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.reviewquestion')),
            ],
            options={
                'verbose_name': 'Answer option',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
